// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3824.PrintedChassisPrototype;
    
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController drivetrainFrontRight;
    public static SpeedController drivetrainFrontLeft;
    public static SpeedController drivetrainRearRight;
    public static SpeedController drivetrainRearLeft;
    public static RobotDrive drivetrainHolonomic;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        drivetrainFrontRight = new Victor(1, 1);
	LiveWindow.addActuator("Drivetrain", "Front Right", (Victor) drivetrainFrontRight);
        
        drivetrainFrontLeft = new Victor(1, 2);
	LiveWindow.addActuator("Drivetrain", "Front Left", (Victor) drivetrainFrontLeft);
        
        drivetrainRearRight = new Victor(1, 3);
	LiveWindow.addActuator("Drivetrain", "Rear Right", (Victor) drivetrainRearRight);
        
        drivetrainRearLeft = new Victor(1, 4);
	LiveWindow.addActuator("Drivetrain", "Rear Left", (Victor) drivetrainRearLeft);
        
        drivetrainHolonomic = new RobotDrive(drivetrainFrontLeft, drivetrainRearLeft,
              drivetrainFrontRight, drivetrainRearRight);
	
        drivetrainHolonomic.setSafetyEnabled(false);
        drivetrainHolonomic.setExpiration(0.1);
        drivetrainHolonomic.setSensitivity(0.5);
        drivetrainHolonomic.setMaxOutput(1.0);

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
